### ISSUE TITLE
Volunteer Pages: Update Details Page

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#17]
### Purpose
You will be working on a very important page for volunteers! More specifically, you'll be working on the `page.tsx` file under the directory `volunteers-remove-details` that lets the volunteers fill in the details of their update to the inventory. After working on this page, you can duplicate and make the necessary adjustments so that we have a similar `page.tsx` file under the directory `volunteers-add-details` that only has the action (remove/add) swapped.

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Implement `volunteer-remove-details/page.tsx` for the "What are you removing?" based on the description and Figma design
  - All the buttons you need can be imported from `components/SurveyButtons.tsx`
  -  The green banner can be imported from `components/UpdateInventoryBanner.tsx`
  - Refer to Helpful Resources below to learn more about how to access colors and text customization
- [x] Work on the new component `Dropdowns.tsx` under the `components` directory
   - [x] Category Name dropdown
   - [x] Item Name dropdown
   - [x] Units dropdown
- [x] Work on the text input field for quantity
- [x] Copy `volunteer-remove-details/page.tsx` to `volunteer-add-details/page.tsx`, since it is going to be the same view but the action ("remove") will be swapped out with "add"
- [x] Create a PR for this ticket
- [x] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

For the green color, please refer to the colors in `globals.css` (specifically, the light-green color)! As an example, you can see how these custom colors were used in `components/SurveyButtons.tsx`. But you can of course customize beyond this and add any colors you think are missing from the current list.

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Button documentation on tailwind: https://daisyui.com/components/button/ For now, it's not going to have any functionality, so no need to be concerned with anything other than styling! (color, background-color, font) There are also buttons that were done as part of the last sprint, so take a look at the `components` directory to see what you can just use!
3. Tailwind dropdown: https://daisyui.com/components/select/
4. Tailwind input field: https://daisyui.com/components/input/

### Pictures
[link](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-843&t=53mSiPNwcURPIQmR-4) to the update details page for action = remove
![Image](https://github.com/user-attachments/assets/0c3bd22d-6fb1-4412-9a23-31f684c3299f)

[link](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=322-1256&t=oX7mHXXW5Gw7ZvMT-4) to the update details page for action = add
![Image](https://github.com/user-attachments/assets/b5b7acaa-12d1-4788-8cf7-6258d43b85cd)
