### ISSUE TITLE
Volunteer Pages: Landing & Confirmation of Action Pages

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#18]
### Purpose
You will be working on very important pages:
1. the landing page for volunteers who will be interacting with the (physical and virtual) inventory! You'll be working on the `page.tsx` file under the directory `volunteers-landing`.
2. the confirmation pages for volunteers to confirm their change to the inventory (so that they don't submit any unwanted changes by accident). There will be 2 confirmation pages depending on if the volunteer is adding an item to the inventory vs removing an item from the inventory. You'll be working on the `page.tsx` files under the directories `volunteers-add-confirm` and `volunteers-remove-confirm`.

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Work on the layout and contents of the pages as per the description and Figma design
  - All the buttons you need can be imported from `components/SurveyButtons.tsx`
  -  The green banner can be imported from `components/UpdateInventoryBanner.tsx`
  - Refer to Helpful Resources below to learn more about how to access colors and text customization
- [x] Use placeholder text for the confirmation page for now for the part that says "Add/Remove [quantity] [units] of [itemName]"
- [x] Once you are done with one of the confirmation pages, copy over whichever one you worked on to the other file, i.e. `volunteers-add-confirm/page.tsx` to `volunteers-remove-confirm/page.tsx` and swap out the action name
- [ ] Create a PR for this ticket
- [ ] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

For colors, please refer to the colors in `globals.css`! As an example, you can see how these custom colors were used in `components/SurveyButtons.tsx`. But you can of course customize beyond this and add any colors you think are missing from the current list.

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Button documentation on tailwind: https://daisyui.com/components/button/ For now, it's not going to have any functionality, so no need to be concerned with anything other than styling! (color, background-color, font)

### Pictures
[link](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-838&t=WMxEzVkKtyazDEGu-4) to landing, [link](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=322-1094&t=WMxEzVkKtyazDEGu-4) to confirmation pages
![Image](https://github.com/user-attachments/assets/24c6aaa2-f899-42ae-8c2a-557257b56497)
![Image](https://github.com/user-attachments/assets/c035f1f2-b8f8-4fb3-9b6c-c9a8d9d6bec1)
