### ISSUE TITLE
Volunteer Pages: Update Saved & Update Not Saved Pages

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#19]
### Purpose
You will be working on very important pages for volunteers! More specifically, you'll be working on the `page.tsx` files under the directories `volunteers-saved` and `volunteers-saved` that lets the volunteers know if their update to the inventory was saved or not.

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Work on the layout and contents of the pages as per the description and Figma design
- [x] Create a PR for this ticket
- [ ] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

For colors, please refer to the colors in `globals.css`! As an example, you can see how these custom colors were used in `components/SurveyButtons.tsx`. But you can of course customize beyond this and add any colors you think are missing from the current list.

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Button documentation on tailwind: https://daisyui.com/components/button/ For now, it's not going to have any functionality, so no need to be concerned with anything other than styling! (color, background-color, font)
3. Check out the pages that were developed as part of the last sprint, namely the `thank you saved` and `thank you unsaved` pages for customers, and see if there are any parallels you can make use of!

### Pictures
[link](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-970&t=WMxEzVkKtyazDEGu-4) to the thank you pages
![Image](https://github.com/user-attachments/assets/7eb593ab-ff9c-425c-805f-57a90325f6f5)
