### ISSUE TITLE
API Endpoints for Demographics

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#21]
### Purpose
You’ve set up the database models and utility functions for `demographics`; now it’s time to bring it all together with API endpoints! This is where the front end will access your hard work.

### TODO
Initial steps:
- [x] move this ticket to the In Progress column
- [x] get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)

API endpoints:
- [x] Open the file called `api/demographics/route.ts` which you began working in last sprint
- [x] Add this line of code to the top of the file: `import { NextRequest, NextResponse } from 'next/server';`. This is how you will directly work with Next.js properties, which is the routing framework our project uses. `NextRequest` and `NextResponse` help us get the server request and lets us easily return the response anytime we try to access the database.
- [x] Below the functions you already wrote, create API endpoints that will wrap the CRUD utility functions you implemented earlier*:
    - [x] `POST /api/demographics` for adding a new entry to the demographics (ex: use the `createDemographic` function you coded as part of the last sprint).
    - [x] `GET /api/demographics` to retrieve all entries.
    - [x] `PUT /api/demographics/[phoneNumber]` to update a single entry by phoneNumber.
    - [x] `DELETE /api/demographics/[phoneNumber]` to delete an entry by phoneNumber.

   How you would actually use NextRequest and NextResponse:
   1. Example function header: `export async function GET(req: NextRequest)`
   2. Example successful response return: `return NextResponse.json(items, { status: 200 });`

*Please make sure you use try/catch statements in your endpoints (Relevant status codes you can use: Bad Request = 400, Unexpected Error = 500, OK = 200, Successfully Created = 201)

Last steps:
- [x] create a PR for this ticket
- [ ] move this ticket to the Ready for Review column

Testing and Documentation:
Use Postman (or any API testing tool) to ensure each endpoint behaves as expected. 
- [x] Check that each endpoint responds with expected data or confirmation.
- [x] Verify response codes for each endpoint (e.g., 201 Created for successful POST, 200 OK for GET).
- [x] Document each endpoint with expected parameters, response codes, and example requests and responses in your PR / ask Jiyoon how to store that info. 
- [x]  Feel free to collab with the back end team that will be working on the Inventory ticket since you'll be working on similar stuff!

### Helpful Resources
More info on rest: https://restfulapi.net/
What is NextRequest?: https://nextjs.org/docs/app/api-reference/functions/next-request
RESTful APIs in 100 Seconds Video: https://www.youtube.com/watch?v=-MTSQjw5DrM
Sample API call examples: https://blog.hubspot.com/website/api-calls
Using postman for testing: https://learning.postman.com/docs/getting-started/overview/

### Our schema
![Image](https://github.com/user-attachments/assets/33375084-4ac7-47c1-8356-644ef5928ca1)
