### ISSUE TITLE
Volunteer Pages: Exit Modal

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#24]
### Purpose
The exit modal will be used throughout both the customer and volunteer pages. You'll be creating an exit modal, which is going to be a component that acts as a pop up window to remind users their progress won't be saved if they exit out of the form. When testing, you'll be using the exit button in the volunteer pages, but your code will eventually be connected to the demographic survey as well!

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Implement `components/ExitModal.tsx` based on the description and Figma design
- [x] Investigate how the visibility of a popup window works, using React's `setState` to know when a button is clicked versus not and using `&&` to determine the visibility of the modal
  - [x] show the modal once button for the modal is clicked
  - [x] hide the modal once cancel is clicked (on the modal)
- [x] direct user to the `volunteer-unsaved` page if exit button is clicked (on the modal)
- [x] Create a PR for this ticket
- [x] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

You are encouraged to use the buttons in `components/SurveyButtons.tsx`.

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Tailwind button: https://daisyui.com/components/button/
3. React useState and setState: https://codedamn.com/news/reactjs/usestate-hook-typescript
4. Visibility and using &&: https://www.dhiwise.com/post/the-ultimate-guide-to-react-click-outside-modal-to-close#:~:text=16-,Integrating%20the%20Modal%20into%20a%20React%20App,-Importing%20and%20Rendering

### Pictures
Feel free to go into the prototype mode Arcadia showed in her demo of the volunteer pages to interact with the exit modal on Figma!

Link to modal [here](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-962&t=SQFZJaQEyewkPymM-4)
![Image](https://github.com/user-attachments/assets/21e59d4d-b59d-401c-8a0c-fce9980625fd)

The popup window should be visible once any of these four exit buttons are clicked! Link to the volunteer pages [here](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-833&node-type=canvas&t=SQFZJaQEyewkPymM-0)
![Image](https://github.com/user-attachments/assets/0a277fcb-2224-4554-b19b-9c73cc4e0ea7)
