### ISSUE TITLE
Customer Pages: Part 1

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#25]
### Purpose
You'll be working on the introductory questions for the customer pages! Namely, you'll be working on the `page.tsx` files in the directories [`customer-action`](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=564-1110&t=SQFZJaQEyewkPymM-4)(take/donate page) and [`customer-donor`](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=564-1484&t=SQFZJaQEyewkPymM-4) (optional survey page).

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Take a look at the `components` directory for components you'll be making use of, i.e. `progressBar.tsx`,` surveyButtons.tsx`, `Dropdown.tsx`, `DemographicsSurveyBanner.tsx`, etc.
- [x] `customer-action`
  - You'll be working on the checkbox component under `components/Checkbox.tsx` that allows user to check both boxes!
  - go to Donor page if "take" not checked
  - don't worry about if take is checked just yet, we'll link to `customer-questions` page if "take" is checked once `customer-questions` is ready
  - Check out the react hooks such as useState and setState to track this information below!
- [x] `customer-donor`
  -  Feel free to draw inspiration from the `volunteers-landing` page / ask the team working on that page for support!
- [ ] create a PR for this ticket
  - [ ] add yourselves as assignees and Jiyoon as the reviewer to the PR
- [ ] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

You are encouraged to use the buttons in `components/SurveyButtons.tsx` and draw inspiration from them for the buttons specific to the pages in this ticket.

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Tailwind button: https://daisyui.com/components/button/
3. Tailwind text field: https://daisyui.com/components/input/
4. React useState and setState: https://codedamn.com/news/reactjs/usestate-hook-typescript

### Pictures
![Image](https://github.com/user-attachments/assets/f21a14b5-e9bf-4b73-bc2c-65330bdccbe5)
![Image](https://github.com/user-attachments/assets/906b6209-fa9d-4abf-b4b4-9f0f8126e678)
