### ISSUE TITLE
Customer Pages: Part 2

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#26]
### Purpose
You'll be working on the set of questions for the customer pages! Namely, you'll be working on the page.tsx file under the directory `customer-questions`, that will be going through five questions as the customer clicks through questions with the next button.

All five of these pages will be their own modules, and their visibilites will be set through React's `useState` and `setState` hooks, in addition to the `&&` syntax (more on this below). You'll be using this functionality, and setting modules visible / invisible based on when the next button for each module is clicked through.

Jiyoon has prepared a doc to walk you through more details [here](https://brick-radius-b7b.notion.site/Customer-Survey-Flow-13c071098b0e80e5a015d42bb0ebbd03).

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Take a look at the `components` directory for components you'll making use of, i.e. `progressBar.tsx`,` surveyButtons.tsx`, `Dropdown.tsx`, `DemographicsSurveyBanner.tsx`, etc.
- [x] Work on `Phone Number module`
  - Create and then use `components/PhoneNumberInput.tsx` based on the existing [Tailwind CSS Input Phone component](https://flowbite.com/docs/forms/phone-input/) and make sure you use the "Phone input country code" component. I'd also include some common Spanish speaking countries to the country codes like Mexico, Colombia, Venezuela, Peru, and Ecuador. (We can customize this further later based on our client's needs.) Refer to the `README` for instructions on how to use Flowbite in Tailwind!
- [x] Work on `Has your information changed? module`
  - Create and then use `components/YesOrNo.tsx` based on the existing [Tailwind Radio Component](https://daisyui.com/components/radio/) and make sure you use the last Radio type called "With label and form-control and custom colors!". The two options will be Yes or No.
  - Once next is clicked:
      - go to `thank-you-saved/page.tsx` if `Yes`
      - make `Full Name module` visible if `No` using `setState`s
- [x] Work on `Full Name module`
  - Look at text field resources below (resources 4-5)
- [x] Work on `Address module`
  - Look at text field resources below (resources 4-5)
- [x] Work on `Household Size module`
  - Look at `components/Dropdown.tsx`! The options should be 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10+
  - Don't prioritize this page as the dropdown component will be done and merged to the codebase as part of the second sprint. Me and Jiyoon will let you know once the dropdown is ready to be added to the module.
- [x] create a PR for this ticket
  - [x] add yourselves as assignees and Jiyoon as the reviewer to the PR
- [x] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

You are encouraged to use the buttons in `components/SurveyButtons.tsx` and draw inspiration from them for the buttons specific to the pages in this ticket.

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Tailwind phone number: https://www.material-tailwind.com/docs/html/input-phone
3. Tailwind button: https://daisyui.com/components/button/
4. Tailwind template for Full Name and Address input: https://tailwindui.com/components/application-ui/forms/form-layouts
5. (Additional resource) Tailwind text field: https://daisyui.com/components/input/
6. Tailwind radio: https://daisyui.com/components/radio/
7. React useState and setState: https://codedamn.com/news/reactjs/usestate-hook-typescript
8. Visibility and using &&: https://www.dhiwise.com/post/the-ultimate-guide-to-react-click-outside-modal-to-close#:~:text=16-,Integrating%20the%20Modal%20into%20a%20React%20App,-Importing%20and%20Rendering

### Pictures (click on the pictures to get to their figma designs)

![Image](https://github.com/user-attachments/assets/492d220e-0163-4045-977f-7c3b7533639a)

 [![Image](https://github.com/user-attachments/assets/7c5cc6ce-7952-4b83-a2da-eb4763664b8b)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=564-1327&t=wj8TlVToRH4UpQCI-4)

[![Image](https://github.com/user-attachments/assets/8501c8ae-13ce-4f30-8ca7-2d1b10bee324)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=564-1063&t=wj8TlVToRH4UpQCI-4)

[![Image](https://github.com/user-attachments/assets/3458d6d2-9766-4f62-bae9-f24babadea4d)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=564-1075&t=wj8TlVToRH4UpQCI-4)

[![Image](https://github.com/user-attachments/assets/f52f1f72-e75f-4775-8780-8b48510b37a0)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=564-1093&t=wj8TlVToRH4UpQCI-4)
