### ISSUE TITLE
Internal View: Spreadsheet

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#31]
### Purpose
You're going to be working on an essential component for the inventory management page! Specifically, you'll be building a spreadsheet-like table that will display inventory items. You'll be working on this under the `inventory/page.tsx` file.

### TODO
- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Open `inventory/page.tsx`
- [x] Create some dummy data that represents inventory items. This data should be structured as an array of arrays, where each sub-array represents a row in the spreadsheet. For example:
  - [x] `const inventoryItems = [
  ['Fruits', 'Apple', 4, 'units'],
  ['Fruits', 'Apple', 5, 'lbs'],
  ['Vegetables', 'Carrot', 10, 'units'],
  ['Grains', 'Rice', 2, 'kg'],
];
`
- [x] For the table structure, use hard-coded column headers (refer to the header names from the Figma design): Last Updated, Category, Item Name, Quantity, Units, Actions
- [x] Implement the table using HTML tags within `inventory/page.tsx`. (refer to Helpful Resources # 1)
`<tr>` stands for table row and is used to define a row in the table.
`<td>` stands for table data and is used to define individual cells within a row.
We don't want to have any empty rows within the spreadsheet, so check out the helpful resources below to see what functions you could make use of so you can traverse through each item within a spreadsheet, and then traverse through each field of each item. Ask us about this if you wanna learn more about this logic and we can talk you through it!
- [x] create a PR for this ticket
  - [x] add yourselves as assignees and Jiyoon as the reviewer to the PR
- [x] move this ticket to the Ready for Review column

For both components, try to see if there is a modular way of going about this, and if you have any questions please let me or Jiyoon know and we can always help!

### Helpful Resources
1. Tailwind table layout: https://tailwindcss.com/docs/table-layout
2. React's map function that would help go through no more than necessary rows: https://legacy.reactjs.org/docs/lists-and-keys.html
3. Use Figma's functionalities to your advantage! Remember you can copy and download icons by right clicking like in the following photo!
![Image](https://github.com/user-attachments/assets/bcfc99e4-7c10-4b0f-8b3d-7628fc2734a9)

### Pictures (click on picture to go to the figma design)
[![Image](https://github.com/user-attachments/assets/fb60ef3e-5041-4c1e-9afd-033b56ec4dc7)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=155-446&t=LUZCYwQxMC0yBC3m-4)
