### ISSUE TITLE
Connecting the FE & BE: Volunteer Pages

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#32]
### Purpose
You'll be handling the functionality of the front end of volunteer pages! This will include the API calls and the redirections that will be happening throughout the pages.

### Set-up
- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Notice that `volunteer-add-pages` and `volunteer-remove-pages` pages manage two modules, whose visibilities are set and changed with React's `useState` hooks.

### Implementation steps
- [x] [`volunteer-landing`](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-838&t=pXAMhlUtEufiBEqw-4)
  - [x] `add` and `remove` buttons should redirect user to the corresponding `volunteer-add-pages` and `volunteer-remove-pages` pages
- [x] [`volunteer-add-pages/page.tsx` ](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=322-1256&t=pXAMhlUtEufiBEqw-4)
  - [x] When the `submit` button is clicked in `VolunteerAddConfirmModule`, check if an entry with the `(itemName, units)` key pair already exists within the database. Consider using `useState<Inventory>` to work with the Inventory interface in the parent module (this will let you store the current inventory object) then pass the inventory item into the modules as props
    - [x] If there is no such item in the inventory yet, create a new entry with the given data `(POST)`
    - [x] If there is such an item in the inventory, update the entry with the given data `(PUT)`
- [x] [`volunteer-remove-pages/page.tsx` ](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-843&t=pXAMhlUtEufiBEqw-4)
  - [x] When the `next` button is clicked in `volunteer-remove-pages`, check if an entry with the `(itemName, units)` key pair already exists within the database.
    - [x] If there is no such item in the inventory yet, display an error message (see error message below).
    - [x] If there is such an item in the inventory, validate that the quantity is valid with the database. Compare quantity in inventory and quantity they want to remove from the inventory:
      - [x] `quantity_update < quantity_in_inventory`: update entry with given data `(PUT)`
      - [x] `quantity_update == quantity_in_inventory`: delete entry `(DELETE)`
        - [x] Call the DELETE endpoint and pass in a JSON object that includes deleteItem and units (because those are the unique identifiers for an inventory item)
      - [x] `quantity_update > quantity_in_inventory` or  `quantity_update < 1`: display error message
        - [x] When quantity is invalid, the `next` button in the `VolunteerRemoveDetailsModule` should not update the visibilities of the two modals (you can use the `disabled` prop that the button already has). 
- [x] Once `submit` is clicked in any of the `volunteer-add-pages` and `volunteer-remove-pages` pages, user should be redirected to the `volunteer-saved` page.
- [x] Add to the `handleBack()` functions in `volunteer-add-pages` and `volunteer-remove-pages` for when the `back` button is pressed in various steps of the update
  - [x] If `back` is clicked when user is has details visible, user should be redirected to the `volunteer-landing` page
  - [x] If `back` is clicked when user is has confirm visible, visibilities of the two modules should be switched
- [x] The `new inventory change` button in [`volunteer-saved`](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-970&t=pXAMhlUtEufiBEqw-4) and [`volunteer-unsaved`](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-977&t=pXAMhlUtEufiBEqw-4) pages should redirect user to `volunteer-landing`
  - [x] The page should go back to `volunteer-landing` after 30 seconds even if user doesn't press the button
- [ ] Error Message
  - [ ] When quantity is invalid (explained above), the `next` button in the `components/volunteer-pages-modules/VolunteerRemoveDetailsModule.tsx` modal should not update the visibilities of the two modals. update the code so that the visibilities are not updated for invalid data (user is not able to move forward with the invalid quantity input). look at how you can change the borders of input text fields to red, and change it back to how it was with the resources below in the `Helpful Resources` section of this ticket. There should also be a text in red appearing near the quantity input field saying "please input a valid number to remove from the inventory" -- this is not in the design, so feel free to show / slack PM&TL&D
- [ ] Create a PR for this ticket
  - [ ] Add yourselves as assignees and Jiyoon as the reviewer to the PR
- [ ] Move this ticket to the Ready for Review column

**Important to mention:** The Exit Modal is being worked on right now, so you can safely assume that whatever code you write and test with `volunteer-saved` will also work for `volunteer-unsaved` since you cannot test that right now.

### Helpful Resources
1. You can play around with React hooks to make the error text visible / invisible in addition to making it go away when user starts typing (through `useState` in combination with `onChange`, etc.)
2. Test with postman as you have done before, but in addition to that, also print to console with `console.log("message")` to make sure the website actually makes those api calls! 
3. Timeout webpages: https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout
4. React useState and setState: https://codedamn.com/news/reactjs/usestate-hook-typescript
5. Visibility and using &&: https://www.dhiwise.com/post/the-ultimate-guide-to-react-click-outside-modal-to-close#:~:text=16-,Integrating%20the%20Modal%20into%20a%20React%20App,-Importing%20and%20Rendering
6. From Jiyoon: Within `volunteer-add-pages`  and `volunteer-remove-pages`, you should look into using the `disabled` button prop which I already added as a prop to all the survey buttons, so that you can use it with useState to validate the inventory inputs.

**How do we access our database?**
We're using [Neon.tech](https://neon.tech/) to host and manage our SQL database. Running the `prisma migrate dev` command applies any pending migration files in our Prisma project to our [Neon.tech PostgreSQL database](https://console.neon.tech/app/projects/bold-dawn-35207560?branchId=br-calm-art-a5bncnhf&database=village-food-hub). This means it creates new tables or modifies existing ones based on the changes in the Prisma schema. These changes are reflected in the Neon.tech dashboard. You'll be able to see the newly created tables, columns, and relationships in your database, or any modifications (like added or removed columns) if you're updating the schema.
