### ISSUE TITLE
GET Inventory

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#38]
### Purpose
For the inventory spreadsheet, we want to be able to fetch the data correctly from the database using a GET call.

### TODO
Initial steps:
- [x] move this ticket to the In Progress column
- [x] get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)

API call:
- [x] Open the file called `inventory/page.tsx` which currently imports the Spreadsheet modal as a component.
- [x] You'll see that the `Spreadsheet` components takes in some arguments to populate it. Study the code to understand which part of the result of `GET` will go into which argument.
- [ ] Write the call to `GET` and store the information in proper variables to pass in to the `Spreadsheet` component!
    - See the example code at the bottom of this code to get you started in the right direction
    - Ensure you use try-catch to safely fetch data
    - We recommend having a function that tries to fetch all the inventory data, then creating another function that extracts the data from the huge list of json objects.
    - Add relevant console logs so you can see the data requests

*(Relevant status codes you can use: Bad Request = 400, Unexpected Error = 500, OK = 200, Successfully Created = 201)

Last steps:
- [x] create a PR for this ticket
  - [x] add yourselves as assignees and Jiyoon as the reviewer to the PR
- [x] move this ticket to the Ready for Review column

Testing and Documentation:
Use Postman (or any API testing tool) to ensure each endpoint behaves as expected. 
- [x] Check that each endpoint responds with expected data or confirmation.
- [x] Verify response codes for each endpoint (e.g., 201 Created for successful POST, 200 OK for GET).
- [ ] Document each endpoint with expected parameters, response codes, and example requests and responses in your PR / ask Jiyoon how to store that info. 

### Helpful Resources
- [How to call a REST API using React](https://mocki.io/call-a-rest-api-in-react)
   - Make sure to replace the example` localhost:3000` with `/api/inventory` so it looks like this: 
```
// some starter code
async function callApi() {
  try {
    const response = await fetch('/api/inventory', { method: 'GET' });
    const inventoryData = await response.json();
    console.log('Inventory items:', inventoryData.data);
    return inventoryData.data;
  } catch (error) {
    console.error('Error fetching inventory items:', error);
    return [];
  }
}
```
