### ISSUE TITLE
Internal View: Login Related Modules

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#39]
### Purpose
You'll be working on the `login/page.tsx` file, which will guide users through six sequential modules to reset their password / log in to the internal view! These modules are:  

1. **WelcomeBack**  
2. **TypeEmail**  
3. **TypeCode**  
4. **TypeResentCode**  
5. **TypeNewPassword**  
6. **ResetSuccess**  

Each of these pages will update only the left side of the interface (title, fields, buttons), while the right-side image and the top-left icon will remain consistent across all modules.  

The visibility of each module will be controlled using React's `useState` and `setState` hooks, along with `&&` syntax to dynamically show or hide components based on button clicks. Right now, there will be no additional checks when progressing through the buttons.

Jiyoon has prepared a doc for a similar structure for the customer flow, which is very similar to this ticket [here](https://brick-radius-b7b.notion.site/Customer-Survey-Flow-13c071098b0e80e5a015d42bb0ebbd03) and we also have similar modularization in `volunteer-add-pages` and `volunteer-remove-pages`. Feel free to reach out to the team that worked on that ticket (Customer Pages Part 2) when you have any roadblocks in addition to Jiyoon & me!

Use the design as a guide, but use your judgment to make it look like the design instead of sticking to the number of pixels, etc. that are in the [Figma](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=128-927&node-type=canvas&t=wIHXInQVwnYSQcse-0) as they might not be the most accurate.

### TODO

- [x] Move this ticket to the In Progress column
- [x] Get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Open `login/page.tsx` and replace code in the file to adhere to the following logic
- [x] Set up variables and functions
  - [x] Add state variables (e.g., `showWelcomeBack`, `showTypeEmail`, etc.) for controlling the visibility of each module.
  - [x] Write handler functions (e.g., `handleNext`) to update these states when each button is clicked. For example, clicking "Send Code" in the **TypeEmail** module should hide **TypeEmail** and show **TypeCode**.
- [x] Basic page
  - [x] Add the pantry image, the logo on the top left corner, and the background color as specified in Figma (add the color to tailwind.config.ts and call it login-green)
- [x] Details of each module
  - [x] **WelcomeBack Module**: On "Sign In" click, navigate to `inventory/page.tsx` and on "Forgot Password?" click, set the **TypeEmail** module visible, therefore transitioning to it
  - [x] **TypeEmail Module**: On "Send Code" click, transition to **TypeCode** 
  - [x] **TypeCode Module**: On "Submit" click, transition to **TypeNewPassword** and on "Resend Code" transition to **TypeResentCode**
  - [x] **TypeResentCode Module**: On "Submit" click, transition to **TypeNewPassword**
  - [x] **TypeNewPassword Module**: On "Submit" click, transition to **ResetSuccess**. 
  - [x] **ResetSuccess Module**: On "Log In" and/or after a timeout of 15 seconds, redirect transition to **WelcomeBack**
- [ ] create a PR for this ticket
  - [ ] add yourselves as assignees and Jiyoon as the reviewer to the PR
- [ ] Move this ticket to the Ready for Review column

### Helpful Resources
About the font/boldness: In your tailwind styling, you can use: `crimson-bold`, `crimson-semibold`, `crimson-regular`, as Jiyoon pre-set in our `globals.css`. You can also just customize the thickness yourself - up to you!

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Tailwind text field: https://daisyui.com/components/input/
3. React useState and setState: https://codedamn.com/news/reactjs/usestate-hook-typescript
4. Visibility and using &&: https://www.dhiwise.com/post/the-ultimate-guide-to-react-click-outside-modal-to-close#:~:text=16-,Integrating%20the%20Modal%20into%20a%20React%20App,-Importing%20and%20Rendering
5. Images via Next.js https://nextjs.org/docs/pages/api-reference/components/image
6. Click on the play button on the top right of the Figma design to experiment and understand how the progression through different pages should work!
![Image](https://github.com/user-attachments/assets/a91049ed-e594-499f-b42b-59a4288d86fc)

### Pictures (click on the pictures to get to their figma designs)
[![Image](https://github.com/user-attachments/assets/cc70ec93-a5a9-483a-9fe9-98a31a1fabbb)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=178-666&t=mtp4n7uefLK9jMPh-4)

[![Image](https://github.com/user-attachments/assets/60880e1f-f163-4e92-835e-f398a5621120)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=854-7163&t=mtp4n7uefLK9jMPh-4)

[![Image](https://github.com/user-attachments/assets/6023b547-4da1-49ae-9fa1-848d96535297)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=854-7182&t=mtp4n7uefLK9jMPh-4)

[![Image](https://github.com/user-attachments/assets/40e3a336-d9da-4b14-84bf-e9b543a4e445)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=854-7244&t=mtp4n7uefLK9jMPh-4)

[![Image](https://github.com/user-attachments/assets/b7eac321-dbde-425f-b3e7-176ea15a810c)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=854-7206&t=mtp4n7uefLK9jMPh-4)

[![Image](https://github.com/user-attachments/assets/f85b4745-c87f-4f06-84fc-1e79b59c214d)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=854-7225&t=mtp4n7uefLK9jMPh-4)
