### ISSUE TITLE
Internal View: Demographics Spreadsheet

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#41]
### Purpose
You will be working on the spreadsheet for the demographics tab! You will be creating a similar component to `components/InventorySpreadsheet.tsx` which is for the inventory and customizing it for the demographics page. You can view the code for the inventory page (`inventory/page.tsx`) to see how the component and page work together.

You can work together with the team that is working on the categories page ticket as they are also building a spreadsheet component. You could also ask the team that worked on the inventory spreadsheet ticket questions you might have in addition to me and Jiyoon!

### TODO
- [x] Move this ticket to the In Progress column
- [x] THIS STEP IS DIFFERENT FROM OTHER TICKETS SO PLEASE BE CAREFUL
  - [x] while in the branch for the navbar ticket, create a new branch (so that it takes the new nav bar code to the new branch). do NOT branch from dev
- [x] Open `demographics/page.tsx` and create `components/DemographicsSpreadsheet.tsx`
- [x] in `demographics/page.tsx`
  - [x] Create dummy data to populate/test the spreadsheet with before the return statement in `demographics/page.tsx`, which will be passed into the call for `components/DemographicsSpreadsheet.tsx`
  - [x] Add the title in. No need to include the count of responses in parentheses, just saying "Demographic Responses" is enough for now! (don't worry about the run report button and the search bar for now)
  - [x] Import the spreadsheet (from `components/DemographicsSpreadsheet.tsx`) and pass in the dummy data properly (view props resources below!)
- [x] in `components/DemographicsSpreadsheet.tsx`
  - [x] refer to `components/InventorySpreadsheet.tsx` and the Figma design
- [ ] create a PR for this ticket
  - [ ] add yourselves as assignees and Jiyoon as the reviewer to the PR
- [ ] move this ticket to the Ready for Review column

### Helpful Resources

About the font/boldness: In your tailwind styling, you can use: crimson-bold, crimson-semibold, crimson-regular, as Jiyoon pre-set in our globals.css. You can also just customize the thickness yourself - up to you!

1. Tailwind table layout: https://tailwindcss.com/docs/table-layout
2. React's map function that would help go through no more than necessary rows: https://legacy.reactjs.org/docs/lists-and-keys.html
3. Props: https://react.dev/learn/passing-props-to-a-component
4. Use Figma's functionalities to your advantage! Remember you can copy and download icons by right clicking like in the following photo!![Image](https://github.com/user-attachments/assets/bcfc99e4-7c10-4b0f-8b3d-7628fc2734a9)

### Pictures (click to get to its figma)
[![Image](https://github.com/user-attachments/assets/d166beed-523a-4472-955c-ab30fc5c1b18)
](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=201-917&t=UeGSzd74ombfoLXz-4)

[![Image](https://github.com/user-attachments/assets/ea32d43d-8fc4-446c-87a4-94f73eb3c317)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=128-928&t=tBisTvQzjAShZrmV-4)
