### ISSUE TITLE
Volunteer & Customer Pages: Form Progression

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#46]
**purpose**
we want customers to put in all of their information for the demographic survey in order to proceed through their respective set of pages

**todo**
- [ ] customer pages
  - [ ] edit the next buttons that help the user progress through the form so that it doesn't move forward if the expected fields are empty / unselected (i.e. invalid).
    - [ ] if next button is clicked when fields are invalid, make the text field border red.
    - [ ] when they start typing / interacting, switch it back to default coloring.
