### ISSUE TITLE
Customer Pages: Welcome page

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#5]
### Purpose
You will be working on a very important page, the landing page to **welcome customers** bringing / taking out food to encourage them to fill out the demographic survey! You'll be working on the `page.tsx` file under the directory `welcome-page`.

### TODO

- [x] move this ticket to the In Progress column
- [x] get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] work on the **Layout**, **Styling and content**, **Button** of the page as per the description and Figma design
- [x] create a PR for this ticket
- [x] move this ticket to the Ready for Review column

### Helpful Resources
1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Button documentation on tailwind: https://v1.tailwindcss.com/components/buttons For now, it's not going to have any functionality, so no need to be concerned with anything other than styling! (color, background-color, font) (you can be creative about the styling for the hover and active modes of the button, and we can run it by Arcadia!)
3. Images via Next.js https://nextjs.org/docs/pages/api-reference/components/image
4. Please take the time to explore Figma - If you click on each element, you'll realize that the sidebar on the right shows you important information about styling that you could really make use of! (click on the picture below for the link directly to the welcome page's figma design) If you have any questions about Figma, feel free to ask me, Jiyoon, or Arcadia, and on the Slack channel!
5. Explore the Github repo - look at the global constants file that Jiyoon prepared and uploaded in the repo to make sure you don't hard code any colors / fonts / etc. There are also the pictures you'll be using for this page :)

### Pictures (click for the figma design)
[![Image](https://github.com/user-attachments/assets/ab9b4282-cb0f-4038-9d1c-9937e07308aa)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=54-52&t=vkLGadcwsw1GmXEg-4)
