### ISSUE TITLE
Customer Pages: Thank You pages

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#6]
### Purpose
You will be working on very important pages, the **thank you pages for customers** who filled out / decided not to fill out the demographic survey! This is a very important page so that customers will come back and fill it again when they next visit the pantry! You'll be creating `page.tsx` files under the directories `saved-thank-you` and `unsaved-thank-you`.

### TODO
- [x] move this ticket to the In Progress column
- [x] get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Part 1: You'll be creating a very integral component to all customer pages: the green banner at the top! You'll be creating this banner titled `DemographicSurveyBanner.tsx` under the `components` directory. Once you are done with this step, please let us know and push as it will help other teams to start working on the other pages of the demographic survey!
- [x] Part 2: work on the **Layout**, **Styling and content**, **Button** of the pages as per the description and Figma designs
- [ ] create a PR for this ticket
- [ ] move this ticket to the Ready for Review column

### Helpful Resources

1. For layout: https://dev.to/drews256/ridiculously-easy-row-and-column-layouts-with-flexbox-1k01
2. Button documentation on tailwind: https://v1.tailwindcss.com/components/buttons For now, it's not going to have any functionality, so no need to be concerned with anything other than styling! (color, background-color, font) (you can be creative about the styling for the hover and active modes of the button, and we can run it by Arcadia!)
3. Images via Next.js https://nextjs.org/docs/pages/api-reference/components/image
4. Please take the time to explore Figma - If you click on each element, you'll realize that the sidebar on the right shows you important information about styling that you could really make use of! (click on the picture below for the link directly to the welcome page's figma design) If you have any questions about Figma, feel free to ask me, Jiyoon, or Arcadia, and on the Slack channel!
5. Explore the Github repo - look at the global constants file that Jiyoon prepared and uploaded in the repo to make sure you don't hard code any colors / fonts / etc. There are also the pictures you'll be using for this page :)

### Pictures 
([click](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=41-244&t=vkLGadcwsw1GmXEg-4) for the figma design)
![Image](https://github.com/user-attachments/assets/5a12e317-5255-4215-ad32-30fa5c330116)

![Image](https://github.com/user-attachments/assets/72466355-7668-4a87-9de9-a5a204c90dc9)
