### ISSUE TITLE
Volunteer & Customer Pages: Required Fields

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#68]
**purpose**
show that all fields in volunteer pages are required for form submission
show that most fields in customer pages are required for survey submission

**todo**
- [ ] volunteer pages
  - [ ] put asterisks next to all four inputs as in the design! (no other functionality) in the `app/volunteer-remove-pages/[[...volunteer-remove-pages]]` and `app/volunteer-add-pages/[[...volunteer-add-pages]]` pages
- [ ] customer pages
  - [ ] please add the asterisks for the following fields:
    - [ ] [action](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=1070-17984&t=zdxKHrGku9aejTNg-4)
    - [ ] [phone number](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=1070-17878&t=zdxKHrGku9aejTNg-4)
    - [ ] [info changed?](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=1070-18269&t=zdxKHrGku9aejTNg-4)
    - [ ] [both fields for full name](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=1070-17891&t=zdxKHrGku9aejTNg-4)
    - [ ] [all except Address 2 in address](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=1070-17926&t=zdxKHrGku9aejTNg-4)
    - [ ] [household size](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=1070-17944&t=zdxKHrGku9aejTNg-4)

**pictures: VOLUNTEER PAGES ONLY -- customer pages designs do not have asterisks**

[![Image](https://github.com/user-attachments/assets/53579e72-9afb-4e66-8b19-f56412158aa2)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=322-1256&t=21udXJf5yrmY9sEo-4)

[![Image](https://github.com/user-attachments/assets/ee17d492-ec2d-4f53-aaf2-9bc350031ccb)](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=315-843&t=21udXJf5yrmY9sEo-4)
