### ISSUE TITLE
Customer Pages: Components

### ISSUE THREAD

**Issue by idil-bit** [JumboCode/village-food-hub#7]
### Purpose
You're going to be working on very important components for the customer pages! Specifically, you'll work on the **progress bar** and **buttons** that will be integral to the customer's user experience. Please let us know as soon as you are done with either of the two components so other teams can begin using them as soon as possible! You'll be creating these components under the directory called `components`.

### TODO
- [x] move this ticket to the In Progress column
- [x] get updated with the codebase (`git checkout dev`, `git pull`, `create a new branch by git checkout -b [branchname]` as per README, `npm install` to update your dependencies, `npm run dev`)
- [x] Progress Bar: You can title each of the five progress bars based on the progress, i.e. `progressBarOne`, `progressBarTwo`, and so on within the `ProgressBars.tsx` file.
- [x] Buttons: You can title each based on their texts, i.e. `buttonExit`, `buttonSubmit`, etc within the `SurveyButtons.tsx` file. The full list is as follows: exit, next, submit, back, cancel, exit anyway.
- [ ] create a PR for this ticket
- [ ] move this ticket to the Ready for Review column

For both components, try to see if there is a modular way of going about this, and if you have any questions please let me or Jiyoon know and we can always help!

Helpful Resources
1. Tailwind progress bar documentation pages: https://flowbite.com/docs/components/progress/
2. Tailwind button documentation pages: https://v1.tailwindcss.com/components/buttons

Pictures
(click [here](https://www.figma.com/design/RsNiTdW8LD11sR0oWS21UW/VFH-Design?node-id=54-304) for the link)
![Image](https://github.com/user-attachments/assets/899a16ed-b92a-4631-a66f-00733b5f723c)
